-- ========================================
-- 最初の3つの九星詳細プロフィール
-- First 3 Star Detailed Profiles
-- 一白水星・二黒土星・三碧木星
-- ========================================

-- 一白水星
INSERT INTO star_profiles (
    star_id, core_essence, cosmic_principle, elemental_reason,
    life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    1,
    '水の如く柔軟にして、どんな形にも適応する。静けさの中に深い知恵を宿す。',
    '一白水星は洛書の「1」北の位置にあり、水の本質を表します。水は低きに流れ、どんな器にも適応し、万物を潤す力を持ちます。冬至の時期に対応し、陰の極まりから陽へと転じる節目の象徴です。',
    '五行において水は「潤下（じゅんか）」の性質を持ちます。下に流れ、万物を潤し、柔軟に形を変えます。水の知恵は、争わずして勝ち、柔よく剛を制する道を示します。',
    '静かな深い知恵で、周囲を潤し、変化に適応しながら確実に進む。',
    '思慮深く内省的。表面は穏やかだが、内に深い感情と知恵を秘める。',
    '静けさと柔軟性の中に真の強さを見出す道。知恵と適応力で人生を切り開く。',
    ARRAY['思慮深い', '柔軟性がある', '適応力が高い', '洞察力に優れる', '忍耐強い', '秘密を守れる'],
    ARRAY['優柔不断', '孤独を好む', '秘密主義', '悲観的', '決断が遅い', '冷たく見える'],
    ARRAY['深い洞察力', '情報収集能力', '分析力', '戦略的思考', '癒しの力'],
    '水到渠成 - 水が流れて自然に溝ができるように',
    ARRAY['研究職', 'ライター', 'カウンセラー', '医療', '哲学者', '心理学者', 'データアナリスト', '秘書'],
    '静かに集中して取り組む。一人で深く考えることを好む。計画的で慎重。分析力を活かす。',
    '知恵と柔軟性で成功する。人脈と情報が鍵。焦らず、時が来るまで待つ忍耐力が重要。',
    '深く静かな愛。感情表現は控えめだが、一途で誠実。理解者を求める。',
    '静かで落ち着いた家庭。家族の癒しとなる。子供の心を理解する。',
    ARRAY['腎臓', '膀胱', '泌尿器系', '冷え性', 'むくみ', 'ストレス', '不眠'],
    ARRAY['体を温める', '適度な水分補給', 'ストレス管理', '瞑想', '規則正しい睡眠', '温泉'],
    '慎重で堅実。無駄遣いを嫌う。貯蓄志向が強い。情報に基づいた判断。',
    '着実な貯蓄と計画的投資。情報を活かした資産形成。不動産投資も得意。',
    '静かで内向的。早くから思慮深い。学業に優れる。内面の世界が豊か。',
    '経験と知恵が深まる。信頼されるアドバイザーとなる。人脈が広がる。',
    '知恵と経験で尊敬を集める。静かな影響力を持つ。精神的な豊かさを得る。',
    ARRAY['黒', '紺', '青', '白'],
    ARRAY['北'],
    ARRAY['水に関するもの', '流れるもの', '曲線のもの', '水晶', '波の絵', '水槽'],
    ARRAY['瞑想', '読書', '温泉', '水辺の散歩', '静かな時間', '知識の習得'],
    ARRAY['優柔不断', '孤立', '秘密主義の行き過ぎ', '冷たい態度', '悲観的思考'],
    ARRAY[
        '上善若水 - 最上の善は水のようなもの',
        '水は方円の器に従う - 柔軟性が強さ',
        '静水深流 - 静かな水は深く流れる',
        '水滴石を穿つ - 継続は力なり',
        '柔よく剛を制す',
        '争わずして勝つ - 水の智慧'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    cosmic_principle = EXCLUDED.cosmic_principle,
    elemental_reason = EXCLUDED.elemental_reason,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 二黒土星
INSERT INTO star_profiles (
    star_id, core_essence, cosmic_principle, elemental_reason,
    life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    2,
    '大地の如く広く受け入れ、全てを育む。母性と献身の象徴。',
    '二黒土星は洛書の「2」南西の位置にあり、大地の母性を表します。坤（こん）の卦に対応し、柔順・受容・育成の性質を持ちます。立秋から秋分の時期に対応します。',
    '五行において土は「稼穡（かしょく）」の性質を持ちます。種を蒔き、育て、収穫する力です。二黒土星の土は、特に「受け入れる土」であり、母なる大地のように全てを包み込みます。',
    '他者を支え、育て、献身的に尽くす。縁の下の力持ちとして社会に貢献する。',
    '優しく献身的。他者のために尽くすことに喜びを感じる。母性愛に満ちている。',
    '無償の愛と献身の中に、真の豊かさと成長を見出す道。',
    ARRAY['献身的', '忍耐強い', '優しい', '面倒見が良い', '堅実', '信頼できる', '地道な努力家'],
    ARRAY['自己主張が弱い', '優柔不断', '流されやすい', '自分を後回し', 'ネガティブ思考'],
    ARRAY['サポート力', '育成能力', '環境整備力', '忍耐力', '調整能力'],
    '厚徳載物 - 厚い徳で万物を載せる',
    ARRAY['看護師', '保育士', '介護', '農業', '不動産管理', '事務', '秘書', '家政婦', 'サポート業務'],
    '地道にコツコツ努力する。サポート役として活躍。周囲のために尽くす。献身的。',
    '継続と献身が成功の鍵。焦らず着実に。信頼を積み重ねることで道が開ける。',
    '献身的で尽くすタイプ。相手を支え、育てる。自己犠牲的になりやすい。',
    '家族のために尽くす。良き母・父となる。家庭を守る柱。',
    ARRAY['胃腸', '消化器系', '疲労', 'ストレス', '婦人科系', '糖尿病'],
    ARRAY['バランスの取れた食事', '適度な休息', 'ストレス管理', '自分の時間を持つ', '断る勇気'],
    '堅実で慎重。貯蓄志向が強い。安定を重視。計画的な金銭管理。',
    '地道な貯蓄と不動産投資。確実な方法で財を成す。相続で財産を得ることも。',
    '控えめで従順。人の面倒を見る。早くから責任を担う。縁の下の力持ち。',
    '信頼と実績を積み重ね、安定した地位を得る。家庭を守り、子を育てる。',
    '家族や社会に貢献した豊かな晩年。孫や後進に慕われる。感謝される。',
    ARRAY['黄色', '茶色', 'ベージュ', '黒'],
    ARRAY['南西'],
    ARRAY['陶器', '土に関するもの', '四角いもの', '農作物', '種', '布'],
    ARRAY['園芸', '料理', 'ボランティア', '瞑想', '自分を大切にする時間', '感謝の実践'],
    ARRAY['自己犠牲', '優柔不断', 'ネガティブ思考', '自己主張の欠如', '過労'],
    ARRAY[
        '大地は全てを受け入れ、育む',
        '陰徳あれば陽報あり - 見えない善行は必ず報われる',
        '継続は力なり',
        '縁の下の力持ちこそが真の強者',
        '与えることで受け取る',
        '母の愛は無限なり'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    cosmic_principle = EXCLUDED.cosmic_principle,
    elemental_reason = EXCLUDED.elemental_reason,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 三碧木星
INSERT INTO star_profiles (
    star_id, core_essence, cosmic_principle, elemental_reason,
    life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    3,
    '雷の如く躍動し、若木の如く成長する。発展と挑戦の象徴。',
    '三碧木星は洛書の「3」東の位置にあり、春の訪れと新しい成長を表します。震（しん）の卦に対応し、雷鳴・発動・成長の性質を持ちます。春分の時期に対応します。',
    '五行において木は「曲直（きょくちょく）」の性質を持ちます。曲がりながらも真っ直ぐ伸びる力です。三碧木星の木は特に若木であり、勢いよく成長し、上へ上へと伸びていきます。',
    '常に成長し、新しいことに挑戦する。行動力と発想力で道を切り開く。',
    '活発で好奇心旺盛。じっとしているのが苦手。新しいことが大好き。',
    '挑戦と成長を続け、自分の可能性を最大限に発揮する道。',
    ARRAY['行動力がある', '発想力豊か', '明るい', '若々しい', '好奇心旺盛', '勇気がある', '前向き'],
    ARRAY['飽きっぽい', '短気', '計画性に欠ける', '落ち着きがない', '衝動的'],
    ARRAY['企画力', '発想力', 'コミュニケーション能力', '営業力', 'プレゼン能力'],
    '木曰曲直 - 木は曲がりながらも真っ直ぐ伸びる',
    ARRAY['営業', '企画', 'マスコミ', '広告', 'イベント', 'スポーツ', '起業家', 'クリエイター'],
    '行動的でスピーディー。新しい企画を次々と提案。チャレンジ精神旺盛。',
    '行動力と発想力が成功の鍵。ただし継続力を意識する。計画を最後まで実行する忍耐も必要。',
    '情熱的で活発。恋愛は積極的。ドラマチックな展開を好む。',
    '活気のある家庭。子供と一緒に楽しむ。成長を促す教育方針。',
    ARRAY['肝臓', '神経系', 'ストレス', '怪我', '事故', '過労'],
    ARRAY['適度な休息', 'ストレス管理', '衝動的行動の制御', '肝臓ケア', '安全運転'],
    '入りも出も激しい。衝動買いしやすい。投資も積極的。リスクを取る。',
    '積極的な事業展開と投資。失敗を恐れず挑戦。早期に成功する可能性も。',
    'エネルギッシュで活発。様々なことに挑戦。失敗も多いが、成長も早い。',
    '経験を積み、落ち着きも出てくる。リーダーとして活躍。事業で成功する。',
    '豊富な経験を活かして後進を指導。なお若々しさを保つ。',
    ARRAY['青', '緑', '水色'],
    ARRAY['東'],
    ARRAY['音の出るもの', '新しいもの', '雷のモチーフ', '若木', '芽', '長いもの'],
    ARRAY['運動', '新しいことへの挑戦', '音楽', '早起き', '計画の見直し'],
    ARRAY['衝動的行動', '短気', '計画の放棄', '飽きっぽさ', '無謀な挑戦'],
    ARRAY[
        '雷は天地を驚かす - 行動で世界を動かす',
        '若木は上へ上へと伸びる',
        '失敗は成功のもと',
        '行動なくして成功なし',
        '挑戦こそが成長の源',
        '勢いは大切だが、継続も必要'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    cosmic_principle = EXCLUDED.cosmic_principle,
    elemental_reason = EXCLUDED.elemental_reason,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 完了メッセージ
SELECT '最初の3つの九星（一白水星・二黒土星・三碧木星）の詳細プロフィールの投入が完了しました！' AS message;
