-- ========================================
-- 残り6つの九星詳細プロフィール
-- Remaining 6 Star Detailed Profiles
-- 四緑木星〜九紫火星
-- ========================================

-- 四緑木星
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    4,
    '風の如く自由で柔軟。調和と人間関係を大切にする。コミュニケーションの象徴。',
    '人と人を繋ぎ、調和をもたらす。風のように自由に、しかし優しく。',
    '社交的で優しい。他者との調和を何よりも重視する。',
    '他者との関わりの中で成長し、調和と平和をもたらす道。',
    ARRAY['社交的', '優しい', '柔軟', '協調性がある', 'コミュニケーション能力が高い', '空気を読む力'],
    ARRAY['優柔不断', '八方美人', '流されやすい', '決断力に欠ける', '自己主張が弱い'],
    ARRAY['仲介能力', 'ネットワーク構築', '調整力', '癒しの力', '人脈形成'],
    '風行天上 - 風が天上を行くように自由に',
    ARRAY['接客業', '人事', 'PR', 'コーディネーター', 'カウンセラー', '旅行業', 'CA', '通訳'],
    'チームワークを大切に。人間関係を活かして成果を出す。調整役として活躍。',
    '人脈とコミュニケーション能力を活かす。人との縁が成功を呼ぶ。',
    '優しく思いやりがある。相手に合わせすぎる傾向も。理想の恋愛を求める。',
    '和やかで調和の取れた家庭を作る。家族の潤滑油的存在。',
    ARRAY['呼吸器系', '神経系', '腸', 'ストレス', '優柔不断による疲労'],
    ARRAY['深呼吸', '適度な運動', '自然との触れ合い', '自己主張の練習', '境界線を引く'],
    'お金より人間関係を優先。計画的ではないが、困らない。人脈が財産。',
    '人脈を活かしたビジネス。信頼関係が財を成す。紹介や仲介で収入を得る。',
    '多くの人と出会い、様々な経験をする。人間関係の基礎を作る時期。',
    '人脈が広がり、社会的な地位を確立。調整役として活躍する時期。',
    '豊富な人脈と経験で、人を繋ぐ役割を果たす。仲人的存在として尊敬される。',
    ARRAY['緑', '青緑', '水色'],
    ARRAY['南東'],
    ARRAY['観葉植物', '香り物', '風鈴', '長いもの', 'スカーフ'],
    ARRAY['旅行', '人との交流', '風通しの良い場所で過ごす', '香りを楽しむ', 'ネットワーキング'],
    ARRAY['孤立', '優柔不断', '八方美人', '自己犠牲', '決断の先延ばし'],
    ARRAY[
        '風は万物に及ぶ - 広く影響を与える',
        '柔よく剛を制す - 柔軟性が強さ',
        '和を以て貴しとなす',
        '人の和が天の時に勝る',
        '縁は異なもの味なもの - 人との出会いを大切に'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 五黄土星
INSERT INTO star_profiles (
    star_id, core_essence, cosmic_principle, elemental_reason,
    life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    5,
    '中央に位置し、全てを統べる帝王の星。強大な力と責任の象徴。',
    '五黄土星は洛書の中心「5」に位置し、唯一、方位を持たない星です。東西南北の全てを統べる中央は、皇帝の座を象徴します。',
    '五行において土は「稼穡（かしょく）」の性質を持ちます。種を蒔き、作物を育てる大地の力です。土は万物を受け入れ、変換し、育てます。五黄土星の人は、この「受容」と「変換」の力を持ちます。',
    'リーダーとして人々を導き、中心的役割を果たす。強い意志で道を切り開く。',
    '強い意志と決断力。支配欲と責任感を併せ持つ。中心にいることを好む。',
    '権力と責任を正しく使い、多くの人を導く道。',
    ARRAY['リーダーシップ', '決断力', '責任感', '統率力', 'カリスマ性', '実行力', '包容力'],
    ARRAY['支配的', '頑固', '独善的', '短気', 'プライドが高い', '孤独'],
    ARRAY['経営能力', '危機管理能力', '人を動かす力', '直感力', '改革力'],
    '中央集権 - 全ての中心として君臨する',
    ARRAY['経営者', '政治家', '管理職', '起業家', 'プロデューサー', 'コンサルタント', '社長'],
    'トップダウン型。強いリーダーシップで組織を率いる。責任を一手に引き受ける。',
    '決断力と実行力で成功を掴む。ただし独善に注意。他者の意見も聞く謙虚さが重要。',
    '情熱的で支配的。相手をリードしたがる。強い愛情を持つが、束縛しがち。',
    '家庭でも中心的存在。強い父性・母性を発揮。家族を守る責任感が強い。',
    ARRAY['胃腸', '循環器', '高血圧', 'ストレス', '過労', '糖尿病'],
    ARRAY['ストレス管理', '適度な運動', 'バランスの取れた食事', '休息', '権力の委譲'],
    '大きく稼ぎ、大きく使う。金銭に対する執着は強い。投資判断は鋭い。',
    '事業経営で大きな富を築く。不動産投資も得意。リスクを取って大きく勝つ。',
    '早くからリーダー資質を発揮。苦労も多いが、それが糧となる。責任ある立場に早く就く。',
    '社会的地位を確立し、多くの人を率いる。最盛期。権力と富を手にする。',
    '経験と実績で、後進を指導。影響力は衰えない。相談役として君臨する。',
    ARRAY['黄色', 'ゴールド', '茶色'],
    ARRAY['中央'],
    ARRAY['高級品', '金属製品', '重厚なもの', '宝石', '王冠', '玉座'],
    ARRAY['瞑想', '権力の正しい使用', '部下への配慮', '謙虚さの維持', 'リーダーシップ研鑽'],
    ARRAY['独善', '傲慢', '過労', '激怒', '孤立', '他者への不信'],
    ARRAY[
        '徳不孤、必有隣 - 徳ある者は孤立せず、必ず助けが来る',
        '王者は力ではなく徳で治める',
        '大権は大責任を伴う',
        '剛健中正 - 強くあれど正しくあれ',
        '高い木は風に折られやすい - 謙虚さを忘れずに',
        '天の時は地の利に如かず、地の利は人の和に如かず'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    cosmic_principle = EXCLUDED.cosmic_principle,
    elemental_reason = EXCLUDED.elemental_reason,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 六白金星
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    6,
    '天の如く高潔にして、金の如く堅固。完璧主義と高い理想の象徴。',
    '高い理想を掲げ、完璧を目指す。正義と秩序を重んじる。',
    '真面目で完璧主義。責任感が強く、妥協を許さない。',
    '天の道を歩み、正義と真理を追求する道。',
    ARRAY['完璧主義', '責任感が強い', '正義感がある', '頭脳明晰', '威厳がある', '高潔'],
    ARRAY['融通が利かない', '頑固', 'プライドが高い', '他人に厳しい', '孤独'],
    ARRAY['分析力', '計画力', '管理能力', '問題解決能力', '戦略立案'],
    '天行健、君子以自強不息 - 天は常に動き、君子は自ら強くなる',
    ARRAY['法律家', '会計士', '技術者', '医師', '研究者', '官僚', '建築家', '技術コンサルタント'],
    '計画的で几帳面。高い基準を設定し、完璧を目指す。細部にこだわる。',
    '専門性と責任感で信頼を得る。長期的なキャリア形成が重要。質の高い仕事で評価される。',
    '真面目で誠実。理想が高く、相手にも高い基準を求める。完璧な関係を望む。',
    '家族への責任を重く受け止める。厳格な父・母となる。高い教育方針を持つ。',
    ARRAY['肺', '呼吸器系', '骨', '歯', '神経系', '完璧主義によるストレス'],
    ARRAY['深呼吸', 'リラックス', '完璧を求めすぎない', '趣味を持つ', '柔軟性を持つ'],
    '計画的で堅実。無駄遣いを嫌い、確実な資産形成を好む。品質重視。',
    '長期的な計画と投資で着実に富を築く。不動産や株式投資に長ける。',
    '真面目で優等生。高い目標に向かって努力する。早熟な一面も。',
    '専門性を活かし、社会的地位を確立。リーダーとして活躍する時期。',
    '威厳と経験で尊敬を集める。後進の指導に力を注ぐ。相談役として重宝される。',
    ARRAY['白', '金', '銀', 'グレー'],
    ARRAY['北西'],
    ARRAY['金属製品', '丸いもの', '高級品', '宝石', '時計', '金貨'],
    ARRAY['規則正しい生活', '瞑想', '深呼吸', '完璧を緩める練習', '専門書を読む'],
    ARRAY['完璧主義の行き過ぎ', '他人への厳しさ', '孤立', '頑固さ', '柔軟性の欠如'],
    ARRAY[
        '天は自ら助くる者を助く',
        '完璧は存在しない、だから追求する価値がある',
        '高潔なる者は孤高なり',
        '正義は我にあり - しかし柔軟性も必要',
        '金は百錬にして精となる - 試練が人を磨く',
        '剛直不阿 - 正義を貫く強さ'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 七赤金星
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    7,
    '秋の実りの如く、豊かさと喜びをもたらす。社交と金運の象徴。',
    '人生を楽しみ、他者にも喜びをもたらす。金銭的成功と人間関係の両立。',
    '明るく社交的。楽しいことが好きで、人を喜ばせることに喜びを感じる。',
    '喜びと豊かさを分かち合い、調和の中に幸福を見出す道。',
    ARRAY['社交的', '明朗快活', '経済感覚に優れる', '愛嬌がある', '器用', '話術に長ける'],
    ARRAY['浪費家', '軽薄', '飽きっぽい', '口が軽い', '計画性に欠ける'],
    ARRAY['営業力', '交渉能力', '金銭感覚', 'エンターテイメント性', '人を楽しませる力'],
    '金声玉振 - 金の音のように響き、玉のように輝く',
    ARRAY['営業', '接客業', '金融', '芸能', '飲食業', '美容', '販売', 'イベントプランナー'],
    '人当たりが良く、顧客との関係構築が得意。楽しみながら働く。明るい雰囲気を作る。',
    '人間関係と経済感覚を活かす。楽しさの中に成功あり。口コミや紹介で広がる。',
    '明るく楽しい恋愛。モテるが、浮気性の傾向も。恋愛を楽しむタイプ。',
    '賑やかで楽しい家庭。子供好きで良き親となる。家族を楽しませる。',
    ARRAY['肺', '口', '歯', '皮膚', '過食', '飲みすぎ'],
    ARRAY['適度な運動', 'バランスの取れた食事', '節制', '口腔ケア', '皮膚ケア'],
    '入るのも早いが出るのも早い。享楽的消費を好む。お金を楽しむタイプ。',
    '収入を増やすと同時に、支出管理も重要。貯蓄の習慣を。金融商品への投資。',
    '人気者で社交的。多くの友人に囲まれる楽しい青春。恋愛経験も豊富。',
    '経済的成功と社会的地位を両立。充実した中年期。人脈が財産となる。',
    '豊かさと人脈に恵まれた晩年。人生を楽しむ。孫に慕われる。',
    ARRAY['赤', 'ピンク', '金', '白'],
    ARRAY['西'],
    ARRAY['金属製品', '丸いもの', '楽器', '装飾品', 'アクセサリー', '鐘'],
    ARRAY['社交', '趣味を楽しむ', '貯蓄の習慣', '節制', 'ネットワーキング'],
    ARRAY['浪費', '暴飲暴食', '軽薄な言動', '計画性のなさ', '口は災いの元'],
    ARRAY[
        '笑う門には福来る',
        '金は天下の回りもの - 惜しまず使い、正しく稼ぐ',
        '人脈は財産なり',
        '楽しみの中にも節度あり',
        '口は災いの元 - 言葉に注意',
        '和して同ぜず - 楽しく付き合うが、流されない'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 八白土星
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    8,
    '山の如く動じず、堅固な意志を持つ。変革と継続の象徴。',
    '困難に動じず、着実に目標に向かう。変化を恐れず、しかし基盤は守る。',
    '真面目で保守的。しかし内には改革の意志を秘めている。',
    '不動の信念を持ちながらも、必要な変化を受け入れる道。',
    ARRAY['堅実', '継続力がある', '真面目', '誠実', '責任感が強い', '努力家'],
    ARRAY['頑固', '融通が利かない', '変化を嫌う', '保守的すぎる'],
    ARRAY['管理能力', '継承力', '改革の実行力', '忍耐力', '不動産運'],
    '艮山止止 - 山のように動じず、止まるべきところで止まる',
    ARRAY['不動産', '建設', '相続業務', '伝統産業', '鉱業', '管理職', '寺社関係'],
    '着実で確実。長期的視点で仕事に取り組む。基盤を固めることを重視。',
    '継続と積み重ねが成功の鍵。急がず、確実に。変化のタイミングを見極める。',
    '真面目で誠実。一途で、簡単には諦めない。安定した関係を好む。',
    '家族と伝統を重んじる。堅実な家庭を築く。先祖を大切にする。',
    ARRAY['関節', '腰', '背中', '胃腸', 'ストレス', '過労'],
    ARRAY['適度な運動', 'ストレッチ', '規則正しい生活', 'リラックス', '腰痛予防'],
    '堅実な貯蓄家。不動産などの実物資産を好む。投機は避ける。',
    '長期的な資産形成と不動産投資。確実な方法で財を成す。相続で財産を得ることも。',
    '真面目で堅実。早くから責任を担い、苦労することも。基礎を固める時期。',
    '蓄積された努力が実を結ぶ。安定と信頼を得る。不動産や財産を築く。',
    '財と経験に恵まれた晩年。後継者を育てる。家督を継承する。',
    ARRAY['白', '黄色', '茶色'],
    ARRAY['北東'],
    ARRAY['山の絵', '石', '陶器', '四角いもの', '不動産', '土地の権利書'],
    ARRAY['登山', '整理整頓', '伝統の継承', '計画的行動', '先祖供養'],
    ARRAY['頑固さ', '変化への抵抗', '過度な保守性', '孤立', '柔軟性の欠如'],
    ARRAY[
        '愚公移山 - 継続は力なり',
        '千里の道も一歩から',
        '山は動かず - 信念を貫く',
        '止まるべきところで止まる知恵',
        '変わらぬもの、変わるもの - 両方を見極める',
        '根を深く張れば、大木となる'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 九紫火星
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    9,
    '太陽の如く輝き、全てを照らす。情熱と知性の象徴。',
    '美と知性を追求し、人々を照らす。情熱をもって人生を生きる。',
    '情熱的で芸術的。直感力に優れ、美しいものを愛する。',
    '内なる光を輝かせ、他者の道を照らす。',
    ARRAY['情熱的', '芸術的センス', '直感力', '華やか', 'カリスマ性', '頭脳明晰'],
    ARRAY['感情的', '短気', 'プライドが高い', '移り気', '派手好き'],
    ARRAY['芸術的才能', 'プレゼンテーション能力', '直感力', 'カリスマ性', '美的センス'],
    '離火明照 - 火が明るく照らすように',
    ARRAY['芸術家', 'デザイナー', '教育者', '医療', '美容', '出版', 'クリエイター', '学者'],
    '情熱的に取り組む。美しさと完成度を重視。人前に出る仕事で輝く。',
    '才能と情熱を活かす。人前に出る仕事で輝く。美的センスが評価される。',
    '情熱的で華やか。理想的な恋愛を求める。ロマンチストで、ドラマチックな展開を好む。',
    '華やかで文化的な家庭。教育熱心な親となる。子供の才能を伸ばす。',
    ARRAY['心臓', '目', '血圧', '神経系', 'ストレス'],
    ARRAY['適度な休息', '目のケア', 'ストレス管理', '感情のコントロール', '冷静さを保つ'],
    '見栄を張りやすい。美しいものや高級品に惹かれる。お金より価値を重視。',
    '才能を活かした収入源。ブランド価値を高めることで成功。知的財産で稼ぐ。',
    '才能が輝く。多くの注目を集め、成功も早い。華やかな青春時代。',
    '社会的地位と名声を得る。最も輝く時期。リーダーや指導者として活躍。',
    '知性と経験で後進を指導。精神的な豊かさを得る。文化的活動に従事。',
    ARRAY['紫', '赤', 'オレンジ', '緑'],
    ARRAY['南'],
    ARRAY['照明', '芸術品', '鏡', '三角形のもの', 'キャンドル', '太陽のモチーフ'],
    ARRAY['芸術鑑賞', '学習', '瞑想', '感情のコントロール', '美しいものに触れる'],
    ARRAY['短気', '見栄', '感情的な決断', '派手すぎる行動', 'プライドによる孤立'],
    ARRAY[
        '火は上に昇る - 向上心を持ち続ける',
        '美は一日にして成らず',
        '知恵は経験から生まれる',
        '光あるところに影あり - 謙虚さを忘れずに',
        '情熱は人生の燃料 - ただし制御も必要',
        '明鏡止水 - 心を鏡のように澄ませる'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 完了メッセージ
SELECT '全9つの九星詳細プロフィールの投入が完了しました！' AS message;
