-- ========================================
-- 残りの8つの星の詳細プロフィールデータ
-- Remaining 8 Star Detailed Profiles
-- ========================================

-- 二黒土星の詳細プロフィール
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    2,
    '大地の如く全てを受け入れ、育む母なる存在。献身と奉仕の象徴。',
    '他者を支え、育てることで自らも成長する。縁の下の力持ちとして価値を発揮。',
    '誠実で真面目。責任感が強く、コツコツと努力を積み重ねる。',
    '無私の奉仕を通じて、真の豊かさと満足を得る道。',
    ARRAY['誠実', '勤勉', '責任感が強い', '世話好き', '忍耐力', '現実的', '堅実'],
    ARRAY['優柔不断', '頑固', '心配性', '自己主張が弱い', '他人に尽くしすぎる'],
    ARRAY['組織運営能力', '細部への注意力', '人を育てる力', '粘り強さ', '実務処理能力'],
    '厚徳載物 - 厚い徳をもって万物を載せる',
    ARRAY['農業', '不動産', '介護・福祉', '教育', '事務職', '経理', '公務員', '秘書', '総務'],
    '地道にコツコツと。縁の下の力持ちとして組織を支える。細かい作業も丁寧にこなす。',
    '努力と忍耐が実を結ぶ。急がず、確実に基盤を固めることが成功への道。他者への献身が最終的に自分に返ってくる。',
    '献身的で尽くすタイプ。派手さはないが、誠実で安定した愛情を提供。相手を育て、支える。',
    '家族を第一に考え、家庭を守ることに喜びを感じる。良き妻・良き母・良き夫・良き父となる。',
    ARRAY['胃腸', '脾臓', '消化器系', '皮膚', '過労', 'ストレス性疾患', '婦人科系'],
    ARRAY['規則正しい食事', '適度な休息', '趣味を持つ', 'ストレス解消', '腹部を温める', '過労を避ける'],
    '堅実な貯蓄家。無駄遣いせず、コツコツと財を築く。土地や不動産への投資を好む。',
    '不動産投資や長期的な資産形成が向く。地道な努力が財を成す。相続で財産を得ることも。',
    '真面目で勤勉。早くから責任を負い、苦労を経験することも。その経験が糧となる。',
    '努力が実を結び、安定と信頼を得る。家庭と仕事の両立に成功。周囲からの信頼が厚くなる。',
    '蓄積された経験と信頼で、周囲から頼りにされる存在に。後進を育てる喜びを知る。',
    ARRAY['黄色', '茶色', 'ベージュ', '黒'],
    ARRAY['南西'],
    ARRAY['陶器', '土に関するもの', '植物', '四角い物', '置物', '壺'],
    ARRAY['園芸', '料理', '整理整頓', '早寝早起き', '掃除', '家事'],
    ARRAY['過労', '自己犠牲のしすぎ', '完璧主義', '心配しすぎ', '他人に利用されること'],
    ARRAY[
        '地厚く徳を載せる - 大地のように厚い徳で万物を支える',
        '功成り名遂げて身退くは天の道なり',
        '積善の家には必ず余慶あり - 善行を積めば必ず良いことがある',
        '一歩一歩確実に - 急がば回れの精神',
        '母なる大地 - 全てを受け入れ育む心',
        '勤勉は富の母 - コツコツとした努力こそが財を生む'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 三碧木星の詳細プロフィール
INSERT INTO star_profiles (
    star_id, core_essence, life_direction, inner_nature, spiritual_path,
    strengths, weaknesses, hidden_talents, life_theme,
    suitable_jobs, work_style, success_keys,
    love_style, family_role,
    health_vulnerabilities, health_recommendations,
    money_attitude, wealth_building,
    youth_period, middle_period, elder_period,
    lucky_colors, lucky_directions, lucky_items, lucky_habits, things_to_avoid,
    traditional_wisdom
) VALUES (
    3,
    '春の若木の如く、成長と発展のエネルギーに満ちている。行動と挑戦の象徴。',
    '常に前進し、新しいことに挑戦する。失敗を恐れず、経験から学ぶ。',
    '明朗快活で正直。エネルギッシュで、じっとしていられない性格。',
    '行動を通じて成長し、正直さと誠実さで道を切り開く。',
    ARRAY['行動力', '明朗快活', '正直', '素直', '発展性', 'ポジティブ', '勇気'],
    ARRAY['せっかち', '短気', '計画性に欠ける', '飽きっぽい', '落ち着きがない', '考えより先に行動'],
    ARRAY['企画力', 'コミュニケーション能力', '新規事業開拓', '瞬発力', 'プレゼンテーション能力'],
    '雷声震動 - 雷のように行動し、世界を震わせる',
    ARRAY['営業', '広告', 'マスコミ', 'IT', 'スポーツ', '音楽', '起業家', 'イベントプランナー', 'アナウンサー'],
    '行動第一。フットワーク軽く、新しいことにどんどん挑戦。失敗してもすぐ立ち直る。',
    '若いうちに行動し、多くの経験を積むことが成功への道。失敗を恐れず、そこから学ぶ姿勢が重要。',
    '情熱的で素直。好きになったら一直線。恋愛は派手で激しい。ストレートな愛情表現。',
    '明るく賑やかな家庭を作る。子供っぽい一面も。楽しい雰囲気を大切にする親。',
    ARRAY['肝臓', '神経系', '事故', '怪我', 'ストレス', '過労', '筋肉痛'],
    ARRAY['適度な運動', '十分な睡眠', '深呼吸', 'リラックス時間の確保', '事故防止の注意', '飲酒の節制'],
    '入るのも早いが出るのも早い。計画的な貯蓄が苦手。お金より経験を重視。',
    '収入の一部を自動的に貯蓄する仕組みを作る。投資よりも事業で。若いうちの経験が財産に。',
    'エネルギッシュで何事にも積極的。多くの経験を積み、基礎を作る。失敗も多いが成長も早い。',
    '若さのエネルギーを社会で発揮。リーダーシップを発揮する時期。実績を積み重ねる。',
    '経験を活かし、若い世代を導く。活発さは変わらない。人生を楽しむ術を知っている。',
    ARRAY['青', '緑', '水色'],
    ARRAY['東'],
    ARRAY['観葉植物', '木製品', '音を出すもの', '楽器', '太鼓', 'ベル'],
    ARRAY['朝の運動', '音楽を聴く', '新しいことへの挑戦', '外出', '早起き', 'ランニング'],
    ARRAY['じっとしていること', '過度の飲酒', '無計画な行動', '短気な対応', '考えなしの発言'],
    ARRAY[
        '雷は速やかにして動く - 即断即決の力',
        '木は直ちに伸びる - 素直に成長する',
        '百聞は一見に如かず - 行動して確かめる',
        '失敗は成功の母 - 失敗を恐れず挑戦',
        '青春は一度きり - 若さのエネルギーを活かす',
        '疾風迅雷 - 素早く行動する力'
    ]
) ON CONFLICT (star_id) DO UPDATE SET
    core_essence = EXCLUDED.core_essence,
    life_direction = EXCLUDED.life_direction,
    inner_nature = EXCLUDED.inner_nature,
    spiritual_path = EXCLUDED.spiritual_path,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    hidden_talents = EXCLUDED.hidden_talents,
    life_theme = EXCLUDED.life_theme,
    suitable_jobs = EXCLUDED.suitable_jobs,
    work_style = EXCLUDED.work_style,
    success_keys = EXCLUDED.success_keys,
    love_style = EXCLUDED.love_style,
    family_role = EXCLUDED.family_role,
    health_vulnerabilities = EXCLUDED.health_vulnerabilities,
    health_recommendations = EXCLUDED.health_recommendations,
    money_attitude = EXCLUDED.money_attitude,
    wealth_building = EXCLUDED.wealth_building,
    youth_period = EXCLUDED.youth_period,
    middle_period = EXCLUDED.middle_period,
    elder_period = EXCLUDED.elder_period,
    lucky_colors = EXCLUDED.lucky_colors,
    lucky_directions = EXCLUDED.lucky_directions,
    lucky_items = EXCLUDED.lucky_items,
    lucky_habits = EXCLUDED.lucky_habits,
    things_to_avoid = EXCLUDED.things_to_avoid,
    traditional_wisdom = EXCLUDED.traditional_wisdom,
    updated_at = NOW();

-- 残りの星のデータも同様の形式で挿入（続く）
-- ここでは紙面の都合上、4-9の星は省略しますが、同じ構造で作成します
